name: ci
on:
  push:
    branches:
      - master
jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: '12'
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Install dependencies
        run: npm ci
      - name: Build packages
        run: npm run build
      - name: Lint packages
        run: npm run lint
      - name: Publish packages to NPM
        run: |
          echo '//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}' > .npmrc
          npm run release -- --yes
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
