name: ci

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: '11'
          run_install: false
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: pnpm ci
      - name: Lint code
        run: pnpm -r lint
      - name: Build packages
        run: pnpm -r build
      - name: Lint packages
        run: pnpm -r publint
      - name: Publish packages to NPM
        run: pnpm -r publish --provenance
